# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
title: Hyperionix Development Center
baseurl: "/" 
url: "https://docs.hyperionix.com"

heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Hyperionix Packages on GitHub":
    - "//github.com/hyperionix/hyperionix"

footer_content: |
  Copyright &copy; 2020 Hyperionix, Inc.
  <script type="application/javascript">
    document.querySelectorAll("div.highlight").forEach(function(h) {
      copy = document.createElement("a");
      copy.appendChild(document.createTextNode("Copy"));
      copy.classList.add("btn");
      copy.style = "position: absolute; right: 0; top: 0";
      copy.onclick = function () {
        var text = h.getElementsByTagName("code")[0].textContent;
        var el = document.createElement("textarea");
        el.value = text;
        el.setAttribute("readonly", "");
        el.style.position = "absolute";
        el.style.left = "-9999px";
        document.body.appendChild(el);
        el.select();
        document.execCommand("copy");
        document.body.removeChild(el);
      };
      h.parentNode.style = "position: relative;";
      h.parentNode.appendChild(copy);
    });
  </script>

ga_tracking: GTM-W8DT5TK

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
