version: "3.5"
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --host 0.0.0.0 --incremental
    ports:
      - 4000:4000
    volumes:
      - ./docs-site/:/srv/jekyll
      - ./bundles/:/usr/local/bundle