version: "3.5"
services:
  jekyll:
    network_mode: "host"
    image: jekyll/jekyll:latest
    command: jekyll serve --host 192.168.71.130 --incremental
    ports:
      - 4000:4000
    volumes:
      - /mnt/hgfs/d/dev/projects/hyperionix/docs/:/srv/jekyll
