version: "3.5"
services:
  jekyll:
    image: jekyll/jekyll:3.8.5
    command: jekyll serve --livereload --force_polling --host 0.0.0.0 --config _config.yml,_config_local.yml
    ports:
      - 4000:4000
      - 35729:35729
    environment:
      JEKYLL_ENV: docker
    volumes:
      - .:/srv/jekyll
